/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DirectMessage {
  'id' : MessageId,
  'content' : string,
  'edited' : boolean,
  'createdAt' : Time,
  'senderUsername' : string,
  'receiverId' : UserId,
  'attachment' : [] | [ExternalBlob],
  'senderId' : UserId,
}
export interface DirectMessageSummary {
  'participant1' : UserId,
  'participant2' : UserId,
  'participants' : [string, string],
  'createdAt' : Time,
  'lastMessage' : [] | [DirectMessage],
  'lastUpdated' : Time,
  'totalMessages' : bigint,
  'participant2Username' : string,
  'unreadCount' : bigint,
  'participant1Username' : string,
  'threadId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'edited' : boolean,
  'createdAt' : Time,
  'senderUsername' : Username,
  'attachment' : [] | [ExternalBlob],
  'senderId' : UserId,
}
export type MessageId = bigint;
export type RoomId = string;
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'username' : Username,
  'displayName' : string,
  'userId' : UserId,
  'createdAt' : Time,
  'isOnline' : boolean,
  'lastSeen' : Time,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGlobalMessage' : ActorMethod<[MessageId], undefined>,
  'fetchGlobalMessages' : ActorMethod<[Time], Array<Message>>,
  'getAllDirectMessagesStats' : ActorMethod<
    [UserId],
    {
      'lastMessageTime' : [] | [bigint],
      'messages' : Array<DirectMessage>,
      'totalCount' : bigint,
      'unreadCount' : bigint,
    }
  >,
  'getAllDirectMessagesWithUser' : ActorMethod<[UserId], Array<DirectMessage>>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDirectMessageThread' : ActorMethod<
    [Principal],
    [] | [Array<DirectMessage>]
  >,
  'getDirectMessageThreadsStats' : ActorMethod<[], Array<DirectMessageSummary>>,
  'getDirectMessagesWithStats' : ActorMethod<
    [Principal],
    {
      'lastMessageTime' : [] | [bigint],
      'messages' : Array<DirectMessage>,
      'totalCount' : bigint,
      'unreadCount' : bigint,
    }
  >,
  'getProfile' : ActorMethod<[UserId], UserProfile>,
  'getSiteLogo' : ActorMethod<[], [] | [ExternalBlob]>,
  'getStatus' : ActorMethod<
    [],
    {
      'canisterTime' : Time,
      'messageCount' : bigint,
      'startupTime' : Time,
      'userCount' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logout' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendDirectMessage' : ActorMethod<
    [Principal, string, [] | [ExternalBlob]],
    undefined
  >,
  'sendMessage' : ActorMethod<[RoomId, string, [] | [ExternalBlob]], undefined>,
  'sendMessageWithAttachments' : ActorMethod<
    [RoomId, string, Array<ExternalBlob>],
    undefined
  >,
  'setSiteLogo' : ActorMethod<[ExternalBlob], undefined>,
  'toggleOnlineStatus' : ActorMethod<[boolean], undefined>,
  'updateBio' : ActorMethod<[string], undefined>,
  'updateDisplayName' : ActorMethod<[string], undefined>,
  'updateMessage' : ActorMethod<
    [RoomId, MessageId, [] | [string], [] | [ExternalBlob]],
    boolean
  >,
  'uploadAvatar' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];