/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageId = IDL.Nat;
export const Time = IDL.Int;
export const Username = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserId = IDL.Principal;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'edited' : IDL.Bool,
  'createdAt' : Time,
  'senderUsername' : Username,
  'attachment' : IDL.Opt(ExternalBlob),
  'senderId' : UserId,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : Username,
  'displayName' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Time,
  'isOnline' : IDL.Bool,
  'lastSeen' : Time,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const RoomId = IDL.Text;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGlobalMessage' : IDL.Func([MessageId], [], []),
  'fetchGlobalMessages' : IDL.Func([Time], [IDL.Vec(Message)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([UserId], [UserProfile], ['query']),
  'getSiteLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'canisterTime' : Time,
          'messageCount' : IDL.Nat,
          'startupTime' : Time,
          'userCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logout' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([RoomId, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'sendMessageWithAttachments' : IDL.Func(
      [RoomId, IDL.Text, IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
  'setSiteLogo' : IDL.Func([ExternalBlob], [], []),
  'toggleOnlineStatus' : IDL.Func([IDL.Bool], [], []),
  'updateBio' : IDL.Func([IDL.Text], [], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [], []),
  'updateMessage' : IDL.Func(
      [RoomId, MessageId, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
      [IDL.Bool],
      [],
    ),
  'uploadAvatar' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageId = IDL.Nat;
  const Time = IDL.Int;
  const Username = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserId = IDL.Principal;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'edited' : IDL.Bool,
    'createdAt' : Time,
    'senderUsername' : Username,
    'attachment' : IDL.Opt(ExternalBlob),
    'senderId' : UserId,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : Username,
    'displayName' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Time,
    'isOnline' : IDL.Bool,
    'lastSeen' : Time,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const RoomId = IDL.Text;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGlobalMessage' : IDL.Func([MessageId], [], []),
    'fetchGlobalMessages' : IDL.Func([Time], [IDL.Vec(Message)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([UserId], [UserProfile], ['query']),
    'getSiteLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'canisterTime' : Time,
            'messageCount' : IDL.Nat,
            'startupTime' : Time,
            'userCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logout' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([RoomId, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'sendMessageWithAttachments' : IDL.Func(
        [RoomId, IDL.Text, IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
    'setSiteLogo' : IDL.Func([ExternalBlob], [], []),
    'toggleOnlineStatus' : IDL.Func([IDL.Bool], [], []),
    'updateBio' : IDL.Func([IDL.Text], [], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [], []),
    'updateMessage' : IDL.Func(
        [RoomId, MessageId, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
        [IDL.Bool],
        [],
      ),
    'uploadAvatar' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };